# Workflow derived from https://github.com/rstudio/shinytest2/tree/main/actions/test-app/example-test-app-description.yaml
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Test app w/ {renv}

jobs:
  test-app:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: release}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2
      
# install (if necessary) the system requirements for your packages
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: |
            make
            gdal-bin
            libssl-dev
            libcurl4-openssl-dev
            libfribidi-dev
            libgdal-dev
            libgeos-dev
            libgeos++-dev
            libharfbuzz-dev
            libicu-dev
            libjq-dev
            libpng-dev
            libproj-dev
            libprotobuf-dev
            libssl-dev
            libtiff-dev
            libudunits2-dev
            libv8-dev
            libxml2-dev
            pandoc
            protobuf-compiler
            libprotoc-dev
            zlib1g-dev
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ${{ join(needs.build.outputs.packages, ' ') }}

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          
# You need a renv.lock in your repo install all the R packages here with this action
      - uses: r-lib/actions/setup-renv@v2

      - uses: rstudio/shinytest2/actions/test-app@v1
        with:
          app-dir: "."
          upload-snapshots: true
